name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=2

    steps:
      - uses: actions/checkout@v4

      # Cache Yarn dependencies
      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Wait for PostgreSQL to be ready
        run: until pg_isready -h localhost -p 5432 -U test_user; do echo "Waiting for postgres..."; sleep 5; done

      - name: Run Migrations
        run: yarn run migrations:test

      - name: Run Tests for app-backend-e2e
        run: yarn test:backend
        env:
          DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
          NODE_ENV: test
